# This workflow will install Claudia after installing Python dependencies, installs rippled ailding-and-testing-python

name: Claudia

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  launch_network_with_claudia:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f ./src/claudia/requirements.txt ]; then pip install -r ./src/claudia/requirements.txt; fi
    - name: Install Claudia locally
      run: |
        python3 setup.py sdist bdist_wheel
        pip install dist/*.tar.gz
        rm -fr build/ dist/ claudia.egg-info
        claudia
    - name: Install rippled with Claudia
      run: |
        claudia rippled install --rippled_branch master
    - name: Start network with Claudia
      run: |
        claudia local-mainnet start
    - name: Stop network with Claudia
      run: |
        claudia local-mainnet stop
